### ISSUE TITLE
Please add a license file, screen shot and a read me

### ISSUE THREAD

**Issue by unixorn** [antoinechab/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by niotna** [comment]
Hello, I just did what you asked me to do. Is everything ok?

**Comment by unixorn** [comment]
One last thing - could you rename the repository to something less generic than zsh-theme? If you don't have anything in mind, antoinechab-theme would be something unique.

**Comment by niotna** [comment]
it's done
